[티거] 로또게임 미션 제출합니다.
Woohan-TDD/java-lotto pull request #4
Opened 2020-06-23 13:57 UTC by kimevanjunseok

안녕하세요. 이제 고생하실 리뷰어님들😂😂

"다시 하길 잘했다." 생각들 정도로 어렵네요....

리뷰....화이팅 하십쇼!!!

2020-06-23 14:32 UTC, ksy90101 requested changes
티거 고생 많았습니다!
전체적으로 코드가 깔끔하네요~
몇가지 피드백을 여기에도 적어볼께요!

1. 클래스 시작({) 이후 어느 클래스에는 한칸이 띄어져 있고, 어느 클래스는 붙어있네요.
이제 팀 프로젝트를 들어가는 시기인데, 하나의 컨벤션을 정해서 통일성을 유지해보는걸 추천합니다!

2. 예외에 대한 메시지들이 모두 없네요....ㅎㅎ 예외 메시지를 넣어보시는걸 추천합니다!

3. 테스트 코드에 @DisplayName()을 안적으시는군요!
테스트 코드 메서드 명이 긴 문장이 될때가 많은데, DisplayName을 사용하면 한글로 쉽게 다들 이해할 수 있지 않을까요!? 한번 고려해보세요~

궁금한 거 있으면 언제든지 DM하시고, 수정 후 다시 리뷰 요청 부탁드려요!

2020-06-23 14:32 UTC, ksy90101 commented on src/main/java/lotto/controller/Controller.java
> +    private static Controller controller = new Controller();
```suggestion
    private static final Controller controller = new Controller();
```
최대한 불변을 유지해보시는게 어떨까요!?

2020-06-23 14:32 UTC, ksy90101 commented on src/main/java/lotto/controller/Controller.java
> +    public void execute() {
예외에 대한 처리가 하나도 안되어있네요...
실행해서 예외가 발생하면 그냥 터져버리네요..
예외 처리를 해보시는게 어떨까요!?

2020-06-23 14:32 UTC, ksy90101 commented on src/main/java/lotto/controller/Controller.java
> +    private List<LottoTicket> createManualTickets(LottoCount manual) {
List도 불변을 위해 Collections.UnmodifiedList()를 해보시는게 어떨까요!?

2020-06-23 14:32 UTC, ksy90101 commented on src/main/java/lotto/domain/LottoTicket.java
> +            throw new IllegalArgumentException();
예외에 메시지를 넣어보아요~

2020-06-23 14:32 UTC, ksy90101 commented on src/main/java/lotto/domain/Money.java
> +            throw new IllegalArgumentException();
예외에 메시지를 넣어보아요!

2020-06-23 14:32 UTC, ksy90101 commented on src/main/java/lotto/domain/Money.java
> +            throw new IllegalArgumentException();
예외에 메시지를 넣어보아요!

2020-06-23 14:32 UTC, ksy90101 commented on src/main/java/lotto/domain/Money.java
> +            throw new IllegalArgumentException();
예외에 메시지를 넣어 보아요!

2020-06-23 14:32 UTC, ksy90101 commented on src/main/java/lotto/view/InputView.java
> +public class InputView {
모두 빈값이 들어가면 예외메시지 없이 프로그램이 터지네요.. ㅎㅎ

2020-06-23 14:32 UTC, ksy90101 commented on src/main/java/lotto/domain/LottoTicket.java
> +public class LottoTicket {
로또 번호가 중복된 티켓이 있어도 생성이 되네요?
예를들어 1,1,2,3,4,5 같은 경우입니다!

2020-06-23 14:32 UTC, ksy90101 commented on src/test/java/lotto/domain/RankTypeTest.java
> +    }
중복 코드가 존재하는데, CsvSoruce를 사용하면 중복 코드를 제거할 수 있을꺼 같아요!

2020-06-23 14:39 UTC, ksy90101 requested changes

2020-06-23 14:39 UTC, ksy90101 commented on src/test/java/lotto/domain/MoneyTest.java
> +public class MoneyTest {
성공하는 테스트도 있어야 하지 않을까요!?

2020-06-23 14:39 UTC, ksy90101 commented on src/test/java/lotto/domain/ManualLottoTicketFactoryTest.java
> +        LottoTicket lottoTicket2 = LottoTicket.from(ticket2);
테스트 코드도 중복 제거가 필요합니다!
중복을 한번 제거해보시는게 어떨까요!?

2020-06-23 14:39 UTC, ksy90101 commented on src/main/java/lotto/domain/LottoCount.java
> +    public boolean isNotZero() {
충분히 테스트를 할 수 있지 않을까요!?

2020-06-23 14:39 UTC, ksy90101 commented on src/main/java/lotto/domain/LottoTickets.java
> +    }
제대로 생성되는지 테스트를 할 수 있을거 같은데, 테스트를 한번 해보시는게 어떨까요!?

2020-06-24 14:18 UTC, YerinCho reviewed
코드나 설계는 깔끔해서 좋아요!! 굿굿 👍 
다만, 럿고가 리뷰해줬던 부분 + 
전반적으로 null에 대한 유효성 검사가 누락된 것 같아요! 
프로그램이 터지면 슬프니까 이에 대한 테스트 + 코드 추가 해주시면 좋을 것 같아요!
그리고 성공하는 케이스들도 테스트하면 더 견고한 프로그램이 되지 않을까 생각합니다 :)

2020-06-24 14:18 UTC, YerinCho commented on src/main/java/lotto/domain/AutoLottoTicketFactory.java
> +    public static AutoLottoTicketFactory from(LottoCount lottoCount) {
lottoCount가 null이면 어떡하죠?!?!

2020-06-24 14:18 UTC, YerinCho commented on src/main/java/lotto/domain/LottoResult.java
> +    public LottoResult(Map<RankType, Integer> countRankType, Money money) {
private으로 접근제한자를 바꿔도 될 것 같은데요?

2020-06-24 14:18 UTC, YerinCho commented on src/main/java/lotto/domain/LottoTicket.java
> +        validateSize(ticket);
사이즈 체크하기 전에 nullPointerException이 터져버리면 어떡하죠!!?

2020-06-24 14:18 UTC, YerinCho commented on src/test/java/lotto/domain/LottoNumberTest.java
> +
정상작동에 대한 테스트 & 예외에 대한 테스트 모두 있으면 더 좋을 것 같아요 :)

2020-06-24 15:44 UTC, ksy90101 approved these changes
코드가 깔끔해졌네요~ 개인적으로 테스트 코드 중복을 제거해보시는 연습을 해보시면 좋을꺼 같아요~
고생많으셨습니다! 간단한 피드백 남기고 approve하겠습니다!

2020-06-24 15:44 UTC, ksy90101 commented on src/main/java/lotto/domain/LottoNumber.java
> +    private static final int MAXIMUM_NUMBER = 45;
protected로 접근제어자를 변경해서 중복을 제거해보는게 어떨까요!?

2020-06-24 15:44 UTC, ksy90101 commented on src/main/java/lotto/domain/LottoResult.java
> +        Objects.requireNonNull(money, "Null 감지");
👍

2020-06-24 15:44 UTC, ksy90101 commented on src/main/java/lotto/domain/LottoTickets.java
> +        lottoTickets.addAll(new ArrayList<>(autoTickets));
```suggestion
        List<LottoTicket> lottoTickets = new ArrayList<>(manualTickets);
        lottoTickets.addAll(autoTickets);
```
이렇게 할수 있지 않을까요!?

2020-06-24 15:44 UTC, ksy90101 commented on src/main/java/lotto/domain/ManualLottoTicketFactory.java
> +
!?

2020-06-24 15:44 UTC, ksy90101 commented on src/main/java/lotto/view/InputView.java
> +        return Integer.parseInt(scanner.nextLine());
Utils을 만들어서 예외를 처리해보는게 어떨까요!?

2020-06-24 15:44 UTC, ksy90101 commented on src/main/java/lotto/view/OutputView.java
> +        System.out.print("(" + type.getPrize() + "원)- ");
printf를 사용해보는게 어떨까요!?

2020-06-24 15:44 UTC, ksy90101 commented on src/test/java/lotto/domain/LottoCountTest.java
> +        assertThat(lottoCount.isNotZero()).isFalse();
CSV를 사용해서 중복을 제거 해보면 어떨까요!?

2020-06-24 15:44 UTC, ksy90101 commented on src/test/java/lotto/domain/LottoNumberTest.java
> +    @ValueSource(ints = {0, 46})
경계값 👍

2020-06-24 15:44 UTC, ksy90101 commented on src/test/java/lotto/domain/LottoTicketTest.java
> +    }
여기도 중복 제거가 가능할꺼 같은데, 어떻게 생각하시나요!?

2020-06-24 15:44 UTC, ksy90101 commented on src/test/java/lotto/domain/WinningLottoTest.java
> +        assertThatThrownBy(() -> WinningLotto.of(input, bonusBall))
저는 개인적으로 예외 테스트에 메시지도 같이 검사를 해야 한다고 생각하는데, 다음 미션에 한번 적용해보시는것도 좋을꺼 같아요~

2020-06-24 15:44 UTC, ksy90101 commented on src/main/java/lotto/view/InputView.java
> +        return lottoTickets;
실제 웹에서는 문자열 또는 Jason만 거의 넘어오는데, InputView를 웹 View라고 생각했을때, 바로 객체가 나오는게 맞을까요!? Converter를 직접 구현해보시는걸 추천합니다~

2020-06-25 07:11 UTC, YerinCho approved these changes
피드백 반영 확인 했고, approve 할게요!
중복되는 코드들을 제거하면 더 나아질 것 같아요 :)
관련해서 의견 하나 남겨놨어요! 티거의 생각대로 해 보면 될 것 같아요~

2020-06-25 07:11 UTC, YerinCho commented on src/main/java/lotto/domain/Money.java
> +        if (money < 1000) {
상수가 놀고있어요!

2020-06-25 07:11 UTC, YerinCho commented on src/main/java/lotto/domain/WinningLotto.java
> +    private void validateHasBonusBall(LottoTicket winningLotto, LottoNumber bonusBall) {
Has 없어도 될 것 같아요 ㅋㅋㅋㅋ 자바블 메소드명 글쓴이 아니신가요!

2020-06-25 07:11 UTC, YerinCho commented on src/main/java/lotto/domain/WinningLotto.java
> +                .map(number -> LottoNumber.from(Integer.parseInt(number)))
전 한번에 끝나는 중간연산을 두 번으로 나눠서 하는 걸 선호하지 않습니다...! 
가독성은 올라가지만 n이 n^2되는걸 좋아하지 않아요!
물론 저의 생각이니 참고만 해주시면 됩니다.

2020-06-25 07:11 UTC, YerinCho commented on src/main/java/lotto/domain/ManualLottoTicketFactory.java
> +        return LottoTicket.from(lottoTicket);
WinningLotto.of()와 하는 역할이 같은 것 같네요! 중복을 줄일 수 있는 방법이 있을까요?
이 메소드를 이용하면 WinningLotto.of()의 길이가 줄 것 같긴 한데 
private로 막혀있기도 하고 이 메소드는 정적메소드가 아니기도 하고... 🧐 티거는 어떻게 생각해요??

2020-06-25 13:04 UTC, kimevanjunseok commented on src/main/java/lotto/domain/LottoNumber.java
> +    private static final int MAXIMUM_NUMBER = 45;
다음 미션때 반영하겠습니다!!!

2020-06-25 13:05 UTC, kimevanjunseok commented on src/main/java/lotto/domain/ManualLottoTicketFactory.java
> +
!?

2020-06-25 13:06 UTC, kimevanjunseok commented on src/main/java/lotto/view/InputView.java
> +        return Integer.parseInt(scanner.nextLine());
다음 미션때 반영하겠습니다!!! Utils 안 만들려다가 놓쳤군요!!

2020-06-25 13:07 UTC, kimevanjunseok commented on src/main/java/lotto/view/OutputView.java
> +        System.out.print("(" + type.getPrize() + "원)- ");
사용했었는데 통일성을 위해 다 print로 했습니다...(printf 사용하면 지저분하게 보이는 것들이 있어서...😂😂)

2020-06-25 13:08 UTC, kimevanjunseok commented on src/test/java/lotto/domain/LottoCountTest.java
> +        assertThat(lottoCount.isNotZero()).isFalse();
다음부터 Boolean검증도 CSV사용하겠습니다!

2020-06-25 13:08 UTC, kimevanjunseok commented on src/main/java/lotto/domain/Money.java
> +        if (money < 1000) {
앗...

2020-06-25 13:09 UTC, kimevanjunseok commented on src/main/java/lotto/domain/WinningLotto.java
> +    private void validateHasBonusBall(LottoTicket winningLotto, LottoNumber bonusBall) {
맞아요...😂😂

2020-06-25 13:12 UTC, kimevanjunseok commented on src/main/java/lotto/domain/ManualLottoTicketFactory.java
> +        return LottoTicket.from(lottoTicket);
따로 만들까 생각도 했지만... 어디에 놔야할지... 또 저것만 빼놓기도 이상하고... 그래서 저런 결단을 한것 같습니다😂😂

2020-06-25 14:43 UTC, merged