[오렌지] 로또 미션 제출합니다.
Woohan-TDD/java-lotto pull request #6
Opened 2020-06-23 18:42 UTC by YerinCho

너무 어렵네요...

근데 수익률 공식이 맞는지 모르겠네요

2020-06-24 08:20 UTC, ksy90101 approved these changes
오렌지 안녕하세요! 고생 많으셨어요~
코드가 깔끔해서, 리뷰 하는데 최대한 쥐어짰네요...ㅠㅠ
다음 블랙잭 미션도 기대가 너무 됩니다! 
간단한 피드백만 남기고 바로 approve하겠습니다! 
아울러, 지금 예외에 대한 처리가 하나도 안되어 있는데, 프로젝트가 그냥 터지지 않고 예외 메시지를 명시 해주시는게 좋을꺼 같아요! 예를들면 Logger가 있겟죠!?

2020-06-24 08:20 UTC, ksy90101 commented on src/main/java/domain/Lotto.java
> +    private final List<LottoNumber> lotto;
상수와 필드는 한칸을 띄어서 구분을 지어주는 것이 좋습니다!

2020-06-24 08:20 UTC, ksy90101 commented on src/main/java/domain/Lotto.java
> +        if (lotto == null || lotto.isEmpty() || lotto.size() != LOTTO_LENGTH) {
어차피 lotto.size() !=6 이 아니라면 예외를 처리한다면 lotto.isEmpty()도 가능한거 아닌가요?
굳이 넣을 필요가 있을까요!?

2020-06-24 08:20 UTC, ksy90101 commented on src/main/java/domain/Lotto.java
> +    public List<LottoNumber> getLotto() {
리스트를 반환할때는 불변을 위해 `Collections.unmodified`를 사용해보시는걸 추천합니다!

2020-06-24 08:20 UTC, ksy90101 commented on src/main/java/domain/LottoFactory.java
> +        return lotto;
여기도 불변을 위해 Collections.unmodified()를 적용해보세요~

2020-06-24 08:20 UTC, ksy90101 commented on src/main/java/domain/LottoFactory.java
> +        return lottoNumbers;
여기도 불변을 위해 Collections.unmodified()를 적용해보세요~

2020-06-24 08:20 UTC, ksy90101 commented on src/main/java/domain/LottoNumber.java
> +    }
어차피 팩토리 메서드라면, 굳이 필요할까요?

2020-06-24 08:20 UTC, ksy90101 commented on src/main/java/domain/purchase/Money.java
> +    private final int money;
여기도 개행을 줘서 상수와 필드를 분리시켜보시면 좋을꺼 같아요.
아울러 지금까지 예외 메시지가 상수화가 안되어 있었는데, 여기만 상수화가 되어 있네요?
팀 프로젝트에 들어가게 된다면 컨벤션이 중요할텐데, 하나를 정하셔서 통일 시켜보시면 좋을꺼 같아요~
이 부분은 개인적으로 취향이라고 생각이 되어서, 편하신 방법으로 통일시켜주면 좋을꺼 같습니다!

2020-06-24 08:20 UTC, ksy90101 commented on src/test/java/domain/purchase/PurchaseCountsTest.java
> +    @NullSource
👍

2020-06-24 08:20 UTC, ksy90101 commented on src/test/java/domain/RankTest.java
> +        Lotto noneLotto = Lotto.createManualLotto(StringUtils.splitToInteger("11,12,13,14,15,16"));
csvSource를 사용한다면, 중복을 줄일수 잇을꺼 같아요!

2020-06-24 08:20 UTC, ksy90101 commented on src/test/java/domain/RankTest.java
> +        assertThat(Rank.findRank(noneLotto, winningLotto)).isEqualTo(Rank.NONE);
이것도 Csv를 사용한다면 줄일 수 있을꺼 같아요.

#### 클린코드 
결국 테스트 함수와 assert문에 관련된 규칙은 아래 2개가 가장 좋다고 하겠다.

개념 당 assert문 수를 최소로 줄여라
테스트 함수 하나는 개념 하나만 테스트하라

2020-06-24 12:48 UTC, kimevanjunseok requested changes
안녕하세요!!오렌지!!
잘 하십니다... 그렇게 다 잘하시면 안된는데...😂😂
몇 가지 피드백 남겨드렸어요!!! 
테스트 관한건 럿고님이 이미 해주셔서 따로 남기진 않았습니다!!!

2020-06-24 12:48 UTC, kimevanjunseok commented on src/main/java/domain/purchase/Count.java
> +        if (money.calculateCount() < manualCount) {
검증을 다른 곳으로 옮기는 것이 메서드가 하나의 일을 하는 것 같아요!!!

2020-06-24 12:48 UTC, kimevanjunseok commented on src/main/java/domain/LottoFactory.java
> +        return lotto;
stream사용하면 간단해 집니다!!!😊

2020-06-24 12:48 UTC, kimevanjunseok commented on src/main/java/domain/LottoNumbers.java
> +        for (int i = MIN_LOTTO_NUMBER; i <= MAX_LOTTO_NUMBER; i++) {
`i`보다 number와 같이 의미있는 이름을 지어주세요!!!(저도 리뷰어에게 받았던 피드백이라서...😂😂)

2020-06-24 12:48 UTC, kimevanjunseok commented on src/main/java/domain/LottoNumbers.java
> +    public LottoNumber valueOf(int number) throws IllegalArgumentException {
`throws IllegalArgumentException` 필요없지 않을까요??

2020-06-24 12:48 UTC, kimevanjunseok commented on src/main/java/domain/Rank.java
> +    SECOND(30_000_000, 5, true, "보너스 번호 일치"),
"보너스 번호 일치" 이런 방법이 있었군요!!!!

2020-06-24 12:48 UTC, kimevanjunseok commented on src/main/java/utils/StringUtils.java
> +public class StringUtils {
https://www.mimul.com/blog/oop-alternative-to-utility-classes/
유틸리티  클래스관해서 저도 받았던 피드백이라서 공유해요!!! 저는 아직 와닿지는 않지만...😂😂

2020-06-24 14:21 UTC, YerinCho commented on src/main/java/domain/Lotto.java
> +        if (lotto == null || lotto.isEmpty() || lotto.size() != LOTTO_LENGTH) {
어 그러네요! 매의눈이십니다

2020-06-24 14:22 UTC, YerinCho commented on src/main/java/domain/LottoNumber.java
> +    }
생각할 거리를 주셔서 고맙습니다! :)

2020-06-24 14:22 UTC, YerinCho commented on src/main/java/domain/purchase/Money.java
> +    private final int money;
사실.. 이 클래스를 먼저 만들다가 그 뒤는 귀찮아서 안..한..거..였..
반영할게요!

2020-06-24 14:23 UTC, YerinCho commented on src/test/java/domain/RankTest.java
> +        Lotto noneLotto = Lotto.createManualLotto(StringUtils.splitToInteger("11,12,13,14,15,16"));
한참 사용을 안하다보니 존재를 잊고있었네요 굿굿

2020-06-24 14:24 UTC, YerinCho commented on src/main/java/domain/LottoNumbers.java
> +    public LottoNumber valueOf(int number) throws IllegalArgumentException {
그러네요 매의눈!

2020-06-24 14:24 UTC, YerinCho commented on src/main/java/domain/Rank.java
> +    SECOND(30_000_000, 5, true, "보너스 번호 일치"),
꼼수입니다 ㅋㅋㅋ

2020-06-24 14:27 UTC, YerinCho commented on src/main/java/utils/StringUtils.java
> +public class StringUtils {
맞아요... 객체지향은 이런 정적 메소드들을 다 싫어하더라구요...

2020-06-25 09:01 UTC, YerinCho commented on src/main/java/utils/StringUtils.java
> +public class StringUtils {
다음 미션부터 적용 해 볼게요!!

2020-06-25 11:40 UTC, kimevanjunseok approved these changes
오렌지!!! 고생하셨어요!!
20000 Approve할게요!! 고생하셨어요!!!
사소한 몇 가지 피드백 남겼습니다!!! 보기만 하셔도 됩니다!!!

2020-06-25 11:40 UTC, kimevanjunseok commented on src/main/java/domain/purchase/PurchaseCounts.java
> +        if (Objects.isNull(autoCount) || Objects.isNull(manualCount)) {
아실지도 모르겠지만 `Objects.requireNonNull(T, String)`를 사용하면 null이면 NPE와 메시지로 String을 반환합니다!!😊

2020-06-25 11:40 UTC, kimevanjunseok commented on src/main/java/domain/Rank.java
> +    private boolean isRank(Lotto lotto, WinningLotto winningLotto) {
아마 `ticket: [1, 2, 3, 8, 9, 10]`이고 `당첨번호: [1, 2, 3, 4, 5, 6], 보너스: 8` 일 때 원하는 Rank는 FIFTH가 나와야하는데 NONE이 나올거예요!! 이유는 로또가 당첨번호와 3개 같고 보너스번호도 같고있기 때문이죠!!! 그냥... 그렇다고요...😂😂

2020-06-25 14:42 UTC, merged